//------------------------------------------------------------------------------
// File        : apb_agent.sv
// Project     : APB UVM Verification Environment
// Description :
//   APB agent encapsulates all APB verification components.
//   It creates and connects the sequencer, driver, and monitor,
//   and distributes the virtual interface to its child components.
//------------------------------------------------------------------------------

class apb_agent extends uvm_agent;
  
  // Register the agent with the UVM factory
  `uvm_component_utils(apb_agent)
  // Virtual interface handle shared by driver and monitor
  virtual dut_if 	vif;
  // APB verification components
  apb_driver 		drv;
  apb_monitor 		mon;
  apb_sequencer 	seqr;
  
  // Constructor
  function new(string name="apb_agent", uvm_component parent);
    super.new(name,parent);
  endfunction
  
  //build phase
  function void build_phase(uvm_phase phase);
    super.build_phase(phase);
    // Retrieve virtual interface from the configuration database
    if(!uvm_config_db#(virtual dut_if)::get(this,"","vif",vif))begin
      `uvm_fatal("NO VIF","NO VIRTUAL INTERFACE IN AGENT")
    end    
    //Create driver, monitor and sequencer
    seqr=apb_sequencer::type_id::create("sequencer",this);
    mon=apb_monitor::type_id::create("monitor",this);
    drv=apb_driver::type_id::create("driver",this);
    
  endfunction
  
  // Connect Phase:This enables the driver to receive transactions generated by the sequence.
  function void connect_phase(uvm_phase phase);
    
    drv.seq_item_port.connect(seqr.seq_item_export);

  endfunction
  
endclass
       
       